name: Auto-deployment of Documentation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0 # Ensures full history for deployment

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: |
        uv pip install --system -e .

    - name: Build documentation
      run: |
        export PATH=$HOME/.local/bin:$PATH
        mkdir gh-pages
        touch gh-pages/.nojekyll
        uv run mkdocs build
        cp -r site/* gh-pages/

    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: gh-pages
        force: true
        folder: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
