name: aurelian QC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Install ROBOT CLI
        run: |
          wget https://github.com/ontodev/robot/releases/latest/download/robot.jar -O /usr/local/bin/robot.jar
          echo '#!/bin/bash' | sudo tee /usr/local/bin/robot > /dev/null
          echo 'exec java -jar /usr/local/bin/robot.jar "$@"' | sudo tee -a /usr/local/bin/robot > /dev/null
          sudo chmod +x /usr/local/bin/robot

      - name: Verify ROBOT Installation
        run: robot --version

      - name: Install dependencies
        run: |
          uv pip install -r pyproject.toml --system -e . --extra gradio --extra gocam --extra rdkit --extra linkml --extra pdfminer
          uv pip uninstall numpy pandas
          uv pip install --no-cache-dir numpy pandas
          uv pip uninstall bioservices || true
          uv pip install bioservices

      - name: Run tests (excluding test_agents)
        run: |
          uv run pytest
